  const nodes = [
    {"id": "start0" , "txt": "&#128075;Hello and welcome! 😊<br/><br/> I\'m your friendly AI-ChatBot here to assist you in learning more about the incredible work and impact achieved by Piramal Foundation. Our foundation is dedicated to solving India\'s most intractable problems through Innovation, Collaboration and Sewa Bhaav. Aligned to the Sustainable Development Goals, Piramal Foundation is committed to improving the lives of marginalized communities, by leveraging the power of youth and strengthening Government systems. We work in collaboration with the Central Government and State Government, international and national organizations and academia to accelerate change in India." , "typ": 1},
    {"id": "start1" , "txt": "Whether you\'re interested in understanding various initiatives under our Big Bets, the accomplishments, or the overall impact we\'ve made, I\'m here to provide you with the information you need. Just let me know which specific area of our work you\'d like to explore, and I\'ll do my best to share the relevant information with you and gladly provide you with insights on the remarkable work carried out by Piramal Foundation." , "typ": 1},
    {"id": "start" , "txt": "How can I assist you today?" , "typ": 1},
    {"id": "bb_options" , "txt": "Kindly choose a Piramal Foundation entity from the list of options. Your selection will direct you to the relevant entity of interest." , "typ": 1},
    {"id": "dbc_options" , "txt": "Explore the DBC Big Bet and delve into our work through these options. Please select your choice." , "typ": 1},
    {"id": "dbc_1" , "txt": "Type your query and ask to learn more about the DBC Big Bet." , "typ": 2 , "dky": "8fed8dba-7205-11ee-ada1-89085e4df2a5" },
    {"id": "dbc_2" , "txt": "<a href=https://www.piramalfoundation.org/digital-bharat-collaborative target=blank>Click here to visit PF DBC Website</a><br/><br/>Learn more about our work -" , "typ": 1},
    {"id": "abc_options" , "txt": "Explore the ABC Big Bet and delve into our work through these options. Please select your choice." , "typ": 1},
    {"id": "abc_1" , "txt": "Type your query and ask to learn more about the ABC Big Bet." , "typ": 2 , "dky": "f1989180-76bb-11ee-b88c-42004e494300" },
    {"id": "abc_2" , "txt": "<a href=https://www.piramalfoundation.org/aspirational-bharat-collaborative    target=blank>Click here to visit ABC Website</a><br/><br/>Learn more about our work -" , "typ": 1},
    {"id": "psl_options" , "txt": "Explore the PSL Big Bet and delve into our work through these options. Please select your choice." , "typ": 1},
    {"id": "psl_1" , "txt": "Type your query and ask to learn more about the PSL Big Bet." , "typ": 2 , "dky": "535cb25c-76bc-11ee-b88c-42004e494300" },
    {"id": "psl_2" , "txt": "<a href=https://www.piramalfoundation.org/piramal-school-of-leadership    target=blank>Click here to visit PSL Website</a><br/><br/>Learn more about our work -" , "typ": 1},
    {"id": "mgr_options" , "txt": "Explore latest indicator & updates from operational projects and programs run under PF umbrella. " , "typ": 1},
    {"id": "mgr_n1" , "txt": "Bihar Beneficiary Count Analysis" , "typ": 3 , "ep": "./mgmt_jsons/BH_beneficiary_analysis_count.json" },
    {"id": "mgr_n2" , "txt": "Bihar Disease Count Analysis" , "typ": 3 , "ep": "./mgmt_jsons/BH_disease_analysis_count.json" },
    {"id": "mgr_n3" , "txt": "Bihar Gender Count Summary" , "typ": 3 , "ep": "./mgmt_jsons/BH_gender_summary_count.json" },
    {"id": "mgr_n4" , "txt": "Bihar Marital  Status Count Analysis" , "typ": 3 , "ep": "./mgmt_jsons/BH_marital_status_analysis_count.json" },
    {"id": "all6bb_ai" , "txt": "Type your quieries and explore all PF entities and Big Bets using AI driven chat." , "typ": 2 , "dky": "5570b808-770d-11ee-b88c-42004e494300" },
    {"id": "thc_options" , "txt": "Explore the THC Big Bet and delve into our work through these options. Please select your choice." , "typ": 1},
    {"id": "thc_1" , "txt": "Type your query and ask to learn more about the THC Big Bet." , "typ": 2 , "dky": "7ee5033e-76bc-11ee-b88c-42004e494300" },
    {"id": "thc_2" , "txt": "<a href=https://www.piramalfoundation.org/anamaya target=blank>Click here to visit PF THC Website</a><br/><br/>Learn more about our work -" , "typ": 1},
    {"id": "psl_options" , "txt": "Explore the PSL Big Bet and delve into our work through these options. Please select your choice." , "typ": 1},
    {"id": "psl_1" , "txt": "Type your query and ask to learn more about the PSL Big Bet." , "typ": 2 , "dky": "535cb25c-76bc-11ee-b88c-42004e494300" },
    {"id": "psl_2" , "txt": "<a href=https://www.piramalfoundation.org/piramal-school-of-leadership  target=blank>Click here to visit PF PSL Website</a><br/><br/>Learn more about our work -" , "typ": 1},
    {"id": "pas_options" , "txt": "Explore the PAS Big Bet and delve into our work through these options. Please select your choice." , "typ": 1},
    {"id": "pas_1" , "txt": "Type your query and ask to learn more about the PAS Big Bet." , "typ": 2 , "dky": "1ed0398c-76bc-11ee-b88c-42004e494300" },
    {"id": "pas_2" , "txt": "<a href=https://www.piramalfoundation.org/piramal-academy-of-sewa   target=blank>Click here to visit PF PAS Website</a><br/><br/>Learn more about our work -" , "typ": 1},
   

    
          ];

        const edges = [
          {"n1": "start" , "n2": "bb_options" , "txt": "Learn about Piramal Foundation" },
          {"n1": "start" , "n2": "mgr_options" , "txt": "Get Project Indicators" },
          {"n1": "bb_options" , "n2": "all6bb_ai" , "txt": "Engage in AI-Driven Chat and Explore All the Big Bets" },
          {"n1": "bb_options" , "n2": "dbc_options" , "txt": "Digital Bharat Collaborative (DBC)" },
          {"n1": "dbc_options" , "n2": "dbc_1" , "txt": "Engage in AI-Driven Conversation" },
          {"n1": "dbc_options" , "n2": "dbc_2" , "txt": "Visit the DBC website" },
          {"n1": "dbc_2" , "n2": "dbc_1" , "txt": "Engage in AI-driven conversation and learn more about DBC Big Bet" },
          {"n1": "dbc_2" , "n2": "bb_options" , "txt": "Keep exploring the work of other Big Bets " },
          {"n1": "bb_options" , "n2": "abc_options" , "txt": "Aspirational Bharat Collaborative (ABC)" },
          {"n1": "abc_options" , "n2": "abc_1" , "txt": "Engage in AI-Driven Conversation" },
          {"n1": "abc_options" , "n2": "abc_2" , "txt": "Visit the ABC website" },
          {"n1": "abc_2" , "n2": "abc_1" , "txt": "Engage in AI-driven conversation and learn more about ABC Big Bet" },
          {"n1": "abc_2" , "n2": "bb_options" , "txt": "Keep exploring other Big Bets & Foundation Entities" },
          {"n1": "mgr_options" , "n2": "mgr_n1" , "txt": "Bihar Beneficiary Count Analysis" },
          {"n1": "mgr_options" , "n2": "mgr_n2" , "txt": "Bihar Disease Count Analysis" },
          {"n1": "mgr_options" , "n2": "mgr_n3" , "txt": "Bihar Gender Count Summary" },
          {"n1": "mgr_options" , "n2": "mgr_n4" , "txt": "Bihar Marital  Status Count Analysis" },
          {"n1": "bb_options" , "n2": "thc_options" , "txt": "ANAMAYA – Tribal Health Collaborative (THC)" },
          {"n1": "thc_options" , "n2": "thc_1" , "txt": "Engage in AI-Driven Conversation" },
          {"n1": "thc_options" , "n2": "thc_2" , "txt": "Visit the THC website" },
          {"n1": "thc_2" , "n2": "thc_1" , "txt": "Engage in AI-driven conversation and learn more about THC Big Bet" },
          {"n1": "thc_2" , "n2": "bb_options" , "txt": "Keep exploring other Big Bets & Foundation Entities" },
          {"n1": "bb_options" , "n2": "psl_options" , "txt": "Piramal School of Leadership (PSL)" },
          {"n1": "psl_options" , "n2": "psl_2" , "txt": "Visit the PSL website" },
          {"n1": "psl_options" , "n2": "psl_1" , "txt": "Engage in AI-driven conversation and learn more about PSL Big Bet" },
          {"n1": "psl_2" , "n2": "bb_options" , "txt": "Keep exploring other Big Bets & Foundation Entities" },
          {"n1": "bb_options" , "n2": "pas_options" , "txt": "Piramal Academy of Sewa (PAS)" },
          {"n1": "pas_options" , "n2": "pas_2" , "txt": "Visit the PAS website" },
          {"n1": "pas_options" , "n2": "pas_1" , "txt": "Engage in AI-driven conversation and learn more about PAS Big Bet" },
          {"n1": "pas_2" , "n2": "bb_options" , "txt": "Keep exploring other Big Bets & Foundation Entities" },
          

           
        ];
      